### ISSUE TITLE
Feature: Remove/Update Command

### ISSUE THREAD

**Issue by ChristianAEDev** [AlexsJones/cli#3]
To be able to update the available commands at run time it would be tremendously helpful if the functions `removeCommand` and `updateCommand` exist.

**Comment by AlexsJones** [comment]
I can look into adding this, this main thing is rebuilding the syntax for the auto prompt, will get back to you when I've done it

**Comment by AlexsJones** [comment]
@ChristianAEDev need your help on how you think this would work at runtime.

So if we had `add` command - what would you be adding? remember it would need some sort of wiring to a function, unless we did something using eval e.g.

```
>>>add specialcommand 'cat ~/file'
OK
>>>specialcommand
'hello'
``` 

I think the only other way would be to use a signal/slot approach of hooking/unhooking from methods e..

``` 
//code..
func unusedcommand() { fmt.Printf("Hello\n")}
```
```
//cli
>>> add runtimebinding 'unusedcommand'
Hello
```

**Comment by ChristianAEDev** [comment]
I'll try my best to explain my use case. Currently my tool has the following *help* output:
```
[read]: Read plans from a config file
[list]: List all available plans
[quit]: Exit the program
[execute]: Run a plan
```
A *plan* consists out of *tasks*. Each *task* describes something to do. This could be renaming a file or extracting a zip archive. So a *plan* basically describes a collection of commands to execute in the given order. (The aim is to automate some reoccurring tasks.)
One or more *plans* are configured in a JSON file. The *read* command reads this file. The *list* command prints out the available *plans*.
Here is where it gets tricky. When the tool is first started it is not aware of any *plans*. These happens only after *read* has been executed.

What I want to achieve is that depending on the *plan* defined in the JSON file I want to add each *plan* as a sub command of the *execute* command.
So if the JSON file has a *plan* called **Install** and a plan called **Update** I want the output of *help* to look like this (and of course have the auto-complete working accordingly):
```
[read]: Read plans from a config file
[list]: List all available plans
[quit]: Exit the program
[execute]: Run a plan
   [Install]: Install in an empty environment
   [Update]: Update the current version
```
Since the JSON file holding the *plans* might change during run time I want the user to be able to just call *read* to update the available commands. For this to work I either need to be able to remove the currently existing command *execute* and add it new or update it.

**Comment by AlexsJones** [comment]
Okay so I think (if we are talking in the context of Cli) the way to do this would be to create a `rootCommand` tree dynamically. It would not be a huge amount of work to add a rootCommand to here https://github.com/AlexsJones/cli/blob/master/cli/cli.go#L18

That would give you the add/remove.

The second challenge would be to hook up adding root commands with your JSON command data. 
However, some sort of callback function might be the way forward on that in code.

If you can show me an example of the JSON file, I can think more on this and have a go?
